### ISSUE TITLE
flutter对html的解析插件 `flutter_widget_from_html` 希望能收录进去帮助更多人

### ISSUE THREAD

**Issue by niyangup** [jahnli/awesome-flutter-plugins#4]
-  url: https://pub.flutter-io.cn/packages/flutter_widget_from_html
- `flutter_html`插件不支持`font-size`等属性,但是上述的插件支持 有需要的小伙伴可以试试 亲测可用

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/96809268-20c8cd00-144d-11eb-98d6-3cc097e57e7b.png)
 已添加，感谢你的贡献 ~
