### ISSUE TITLE
推荐一个indexedstack的懒加载插件 还有一个同家的dialog

### ISSUE THREAD

**Issue by dilsods** [jahnli/awesome-flutter-plugins#6]
[https://pub.dev/packages/proste_indexed_stack](url)
懒加载package 可以部分页面预加载

[https://pub.dev/packages/proste_dialog](url)
一个dialog 预设了一部分动画提示觉得还可以 也可以自己做 还封装了广告图片的弹窗

**Comment by jahnli** [comment]
好的，会整理加载。谢谢。
