### ISSUE TITLE
提供一些有意思的插件

### ISSUE THREAD

**Issue by lanmaoGit** [jahnli/awesome-flutter-plugins#7]
针对dart和flutter的lint插件
[https://pub.dev/packages/lint](url)

提供点坐标,用更简单的方法通过ClipPath裁剪二阶贝塞尔曲线和三阶贝塞尔曲线 也提供了计算点坐标的方法
[https://pub.dev/packages/proste_bezier_curve](url)

clippath裁剪组件后后绘制相应路径的阴影效果
[https://pub.dev/packages/proste_shadow_clip](url)

dialog的弹出动画
[https://pub.dev/packages/flutter_animated_dialog](url)

**Comment by jahnli** [comment]
thanks，我将在下次更新时添加。
